version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery_worker
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React served via Nginx
    depends_on:
      - backend
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    working_dir: /app
    command: celery -A celery_worker.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_data: {} 
