"""Add message_id to email_logs

Revision ID: 94db7a122d04
Revises: b60934fe48be
Create Date: 2025-09-10 23:00:51.549394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94db7a122d04'
down_revision = 'b60934fe48be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('message_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_email_logs_message_id'), 'email_logs', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_logs_message_id'), table_name='email_logs')
    op.drop_column('email_logs', 'message_id')
    # ### end Alembic commands ###
