name: Build and Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -saulverae/fastapi-inbox-automation:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push saulverae/fastapi-inbox-automation:latest

      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          ssh_args: "-o StrictHostKeyChecking=no"
          command_timeout: "5m"
          script: |
            echo "✅ Connected to EC2"
            cd /home/saulvera/fastapi-inbox-automation || exit 1 # adjust to your app directory
            docker compose pull
            docker compose down
            docker compose up -d
            docker compose ps
